### ISSUE TITLE
Got "undefined  is not an object (evaluating  'RCTToastAndroid.SHORT')"

### ISSUE THREAD

**Issue by Bing-Xia** [vonovak/react-native-simple-toast#1]
Hi, I tried this component in my project, and react-native version is 0.42.3,

I did the steps you mentioned include `react-native link react-native-simple-toast`, then import the module to my page component, then the issue came out
![image](https://cloud.githubusercontent.com/assets/9410789/25954266/4bbe6538-3698-11e7-83a5-80998e85c0a1.png)
I tried to find some inspiration from google, but failed.
did I missed something? thanks a lot :) btw, it works well on android

**Comment by iamhardik08** [comment]
rebuild using react-native run-ios

**Comment by vonovak** [comment]
@Bing-Xia did rebuilding solve this?

**Comment by Bing-Xia** [comment]
@vonovak  sorry, not yet, I will add new comment when the issue get resolved, thank you all

**Comment by Bing-Xia** [comment]
It's clear now, I made the incorrect steps to involve this module, since I ignored the `build failed` result of `run-ios`. so make sure to build app succeed and this module will added succeed. 
Thanks for your help~

**Comment by tiaaaa123** [comment]
I got this issue, but my build is working fine

**Comment by vonovak** [comment]
@tiaaaa123 expo does not allow custom native modules as far as I know

**Comment by Leafyyuki** [comment]
@vonovak I also got this issue with using Expo 31. Is there any solution?

**Comment by vonovak** [comment]
This does not work with expo, you'll need to use a JS-only solution.
