### ISSUE TITLE
toast message is always appearing at bottom and short time duration

### ISSUE THREAD

**Issue by mohity777** [vonovak/react-native-simple-toast#1]
i have used toast as==>

Toast.showWithGravity('This is a long toast at the top.', Toast.LONG, Toast.TOP);

still the toast message is appearing at bottom and for short duration

**Comment by vonovak** [comment]
@mohity777 hello and thanks for reporting. What platform is that on?

**Comment by mohity777** [comment]
andrp

> @mohity777 hello and thanks for reporting. What platform is that on?

on android

**Comment by KrisLau** [comment]
I am experiencing the same thing and I noticed you closed the issue. What did you do to fix it?

**Comment by lumigj** [comment]
> @mohity777 I am experiencing the same thing and I noticed you closed the issue. What did you do to fix it?

I also experiencing the same issue on an android device. What is ur phone? I use samsung s10

**Comment by nijarv** [comment]
@mohity777 and @vonovak,  I am also experiencing the same issue, I use Samsung M13. Is there a solution to this issue?

**Comment by mohity777** [comment]
I actually can't remember this, but it stopped happening after sometime. might be chances that i switched to another phone.
