### ISSUE TITLE
Error when building project 

### ISSUE THREAD

**Issue by zaid0077** [vonovak/react-native-simple-toast#10]
when i build this project it gives me error saying that:  Error While trying to resolve module `react-native-simple-toast` The package was downloaded successfully  However, this package itself specifies a `main` module field that could not be resolved 

 "react-native": "0.63.2",

**Comment by vonovak** [comment]
hello, I'm sorry but I do not have such issue. Closing.

**Comment by davekedar** [comment]
I have the same issue plz help @vonovak @zaid0077 

![image](https://user-images.githubusercontent.com/11268363/130388279-c540784b-dc4d-4411-9bc8-110c8cbcebaf.png)
