### ISSUE TITLE
Does it support showWithGravityAndOffset()?

### ISSUE THREAD

**Issue by Yandamuri** [vonovak/react-native-simple-toast#12]
Toast is appearing by touching bottom of the screen. is there any possibility to add some spacing around Toast message

**Comment by vonovak** [comment]
hello, we do not support this but a PR for this would be merged :)

**Comment by Yandamuri** [comment]
@vonovak Thank You for your response. I am new to react-native and not sure about this PR. Do mean, If I write the cod for this feature and you will merge to the library, right!. Please correct me if I am wrong

**Comment by vonovak** [comment]
Hello, yes, that is correct
