### ISSUE TITLE
CSToastPositionBottom of type NSString cannot be converted to NSNumber on IOS

### ISSUE THREAD

**Issue by SupriyaGo** [vonovak/react-native-simple-toast#13]
when implementing on ios getting this error CSToastPositionBottom of type NSString cannot be converted to NSNumber.

**Comment by MaeenBadea** [comment]
I'm getting the same error

**Comment by SupriyaGo** [comment]
@MaeenBadea use only this line and you will not get this error - Toast.show("your message") , that's it.
