### ISSUE TITLE
TypeError: null is not an object (evaluating 'RCTToast.SHORT') - non expo projects

### ISSUE THREAD

**Issue by sabarishnarain** [vonovak/react-native-simple-toast#16]
RN version 69.
react-native-simple-toast: 1.1.3

Forked from https://github.com/vonovak/react-native-simple-toast/issues/7, this happens in non-expo projects as well.

**Comment by umer-qureshi-tv** [comment]
Any solutions to this ?

**Comment by kuldeepworkid** [comment]
@sabarishnarain have you tried this steps after installing

1. cd ios && pod install
2. Re-install the app.

**Comment by OskarD** [comment]
I have this problem too, but I didn't eject my application

**Comment by vonovak** [comment]
closing as no repro was provided
