### ISSUE TITLE
[Feature request] Allow a Text component as Toast message

### ISSUE THREAD

**Issue by KrisLau** [vonovak/react-native-simple-toast#17]
Hi, this component has been super useful! It would be nice if we could use a Text component as the input for the `message` prop in `Toast.show` and `Toast.showWithGravity`. I was hoping to put an icon in my toast message which is isn't possible in its current state.

**Comment by kuldeepworkid** [comment]
@KrisLau this library doesn't support icon and custom view. I think this library may help you [https://www.npmjs.com/package/react-native-toast-message](url)

**Comment by KrisLau** [comment]
@kuldeepworkid Thanks!
