### ISSUE TITLE
Missing homepage from package.json causes podspec to fail installation

### ISSUE THREAD

**Issue by xeroxoid** [vonovak/react-native-simple-toast#18]
When installing the pod via pod install (after adding the lib) the following validation error appears:

```[!] The `react-native-simple-toast` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.```

This can be easily fixed by adding the `homepage` property to the package.json

**Comment by vonovak** [comment]
@xeroxoid thanks for reporting, could you please ship a PR that fixes this? Thank you!

**Comment by xeroxoid** [comment]
Done :)

Will close the issue once merged.
