### ISSUE TITLE
Accessibility support

### ISSUE THREAD

**Issue by kashmiry** [vonovak/react-native-simple-toast#19]
Is it possible to support something like accessibilityAnnouncement, so users who use the app and depend on the voice over can hear the message from the Toast?
Currently when a toast is trigger a voice over is not set for the message so a user with accessibility will not get it.

**Comment by vonovak** [comment]
hello, thanks for asking. I do not know the answer to that, you'll need to investigate it. Thank you! 🙂

**Comment by phazei** [comment]
💢 💢 💢
