### ISSUE TITLE
showWithGravity, position does not work with position

### ISSUE THREAD

**Issue by orkundurmaz** [vonovak/react-native-simple-toast#20]

**Comment by knightmate** [comment]
Hello Admin,
can you please assign this issue to me?

**Comment by lloydwatkin** [comment]
@paulmckiller are you seeing this on Android? `ToastAndroid` seems to be ignoring position for me right now when used directly.

**Comment by KrisLau** [comment]
> Hello Admin, can you please assign this issue to me?

@vonovak

**Comment by imavipatel** [comment]
did you find any solution regarding position in ToastAndroid
