### ISSUE TITLE
Android not showing toasts at all

### ISSUE THREAD

**Issue by KrisLau** [vonovak/react-native-simple-toast#21]
The toast is not popping up at all for me on android. At first I thought it was because of the layout of my screen but after testing it on a number of screens, it seems like it is totally not working.

**Comment by KrisLau** [comment]
Tested using a snack: https://snack.expo.dev/@kris_lau/toast-android-api-example and it seems to work there so it seems like it might have to do with just updating my react native packages especially since I would assume it would use ToastAndroid from react native

**Comment by jamesjara** [comment]
Having the same issue, any idea?

**Comment by iamabhi9v** [comment]
Not working on android
