### ISSUE TITLE
Toast is not appearing immediately after dismissing modal.

### ISSUE THREAD

**Issue by krushalikevadiya** [vonovak/react-native-simple-toast#23]
I have displayed toast immediately after dismissing modal but it is not showing in iOS only.in Android it is working properly.
Any solution?

**Comment by vonovak** [comment]
hello and thanks for asking. Did you read the usage part of the raeadme? Thank you :)

**Comment by krushalikevadiya** [comment]
Yes I have read it but didn't get exact idea so can you please give me example with code?

**Comment by imavipatel** [comment]
> hello and thanks for asking. Did you read the usage part of the raeadme? Thank you :)

toast is not working with gravity it is showing on bottom by default  center and top is not working in android 12 when using target sdk 31 please look into this 
thank you
