### ISSUE TITLE
null is not an object (evaluting 'RCTToast.SHORT')

### ISSUE THREAD

**Issue by govind1530** [vonovak/react-native-simple-toast#24]
React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 195.56 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.3 => 0.58.3 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-contacts-wrapper: 0.2.4

when import libeary in screen.

**Comment by smity81435** [comment]
Same Issue...

**Comment by vonovak** [comment]
hi! Please add a runnable repro of this issue, otherwise I won't be able to help. see https://stackoverflow.com/help/minimal-reproducible-example

**Comment by oxyii** [comment]
@govind1530 @smity81435 same issue because I forgot to run `pod install`. Please make sure you did it

**Comment by ireeskenz** [comment]
> @govind1530 @smity81435 same issue because I forgot to run `pod install`. Please make sure you did it

What is your version of react-native ? Because it doesn't work for me on RN 0.61.5

**Comment by oxyii** [comment]
@ireeskenz I'm not sure that RN version is important. As I understand, this red screen shown when **native** part of lib is not installed correctly. What's all. My RN version `"react-native": "0.61.4"`

**Comment by ireeskenz** [comment]
@oxyii so you confirm that in IOS, your project work without issue with react-native-simple-toast ?

**Comment by oxyii** [comment]
@ireeskenz 
![1RsX-yZTDW0](https://user-images.githubusercontent.com/39907210/69496350-6352f400-0ee2-11ea-89c5-f47dfa06dceb.jpg)

**Comment by ireeskenz** [comment]
I retried finally and that's work !! Thank's you very much

**Comment by oxyii** [comment]
@vonovak I think you can make accent on installing native part of this lib in README and close this issue

**Comment by vonovak** [comment]
I improved the Readme a couple days back in  https://github.com/vonovak/react-native-simple-toast/commit/4a17c7c011e02a418e4c11c33c927aa6e5d9aa82

Closing as resolved
