### ISSUE TITLE
'RNSimpleToastSpec.h' file not found

### ISSUE THREAD

**Issue by KrisLau** [vonovak/react-native-simple-toast#27]
Getting this error:
```
'RNSimpleToastSpec.h' file not found
```
when I update the package from 1.1.4 to 2.0.0. I think it has something to do with the `use_frameworks!` that is required to use `react-native-firebase`

**Comment by vonovak** [comment]
hello, are you building using the new architecture?

thank you

**Comment by KrisLau** [comment]
@vonovak Nope old architecture

EDIT: I just saw that it said new arch is required my bad. So is the old architecture being phased out for RN?

**Comment by vonovak** [comment]
@KrisLau many libraries that are migrating are supporting both old and new arch at the same time. However, for this lib I chose to only support new arch going forward because the code is more straightforward that way. But yes, ultimately the old arch will be phased out.

**Comment by KrisLau** [comment]
@vonovak Oh ok I see, thank you!
