### ISSUE TITLE
Compiling code shows 'UIView+Toast.h' file not found

### ISSUE THREAD

**Issue by jamesawer3** [vonovak/react-native-simple-toast#27]
I'm using below react config and I manually linked it with XCode still I'm getting this error I couldn't compile the code

```
React Native Environment Info:
    System:
      OS: macOS 10.15.1
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 1.21 GB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      npm: 6.13.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

![Screen Shot 2019-12-02 at 6 56 15 PM](https://user-images.githubusercontent.com/43437378/69963138-8fe7bb00-1535-11ea-990a-2648f1a1612d.png)

**Comment by vonovak** [comment]
Hi! For RN < 0.60, please install the version before 1.0.0

**Comment by vonovak** [comment]
Or you can try installing the native dep according to the instructions here https://github.com/scalessec/Toast

That might also work

**Comment by garmoshka-mo** [comment]
`"react-native-simple-toast": "0.1.1"` worked for me
would be good to add it to readme

**Comment by garmoshka-mo** [comment]
Sorry, this allows to compile project, though toast not shown on iOS. 
Solution is to replace  `react-native-simple-toast` to `react-native-root-toast`
