### ISSUE TITLE
'RNSimpleToastSpec.h' file not found

### ISSUE THREAD

**Issue by SuryaVenkat** [vonovak/react-native-simple-toast#30]
Hi, I have implemented in one of my react native project in android it is working fine but for iOS we are getting below error
'RNSimpleToastSpec.h' file not found

Done removing the pod and install again but no use 

version implemented : "react-native-simple-toast": "^2.0.0",
React native version :  "0.70.4"

**Comment by vonovak** [comment]
please see #27 and #29

does that answer the question?

**Comment by SuryaVenkat** [comment]
Hi, I couldn't find any solution from your reference.
Kindly let me know what needs to be done.

**Comment by Vishnu-Nalagatla** [comment]
I am also facing the same issue in :

    "react": "17.0.2",
    "react-devtools": "^4.27.1",
    "react-native": "0.66.4",

    "react-native-simple-toast": "^2.0.0",

**Comment by vonovak** [comment]
you need to run pod install like this: `RCT_NEW_ARCH_ENABLED=1 pod install` so that new architecture is enabled.

@Vishnu-Nalagatla please see here: https://github.com/vonovak/react-native-simple-toast#install RN 0.70 is required

Thank you
