### ISSUE TITLE
'RNSimpleToastSpec.h' file not found

### ISSUE THREAD

**Issue by shaheerahmed1997** [vonovak/react-native-simple-toast#32]
Hey there i have checked your answer related to Pod install in ios issue when using new architecture of react native i.e 0.7x . The answer is already mentioned in the documentation by adding RCT_NEW_ARCH_ENABLED=1 when installing pod. But the thing that bother me that do i need to do that thing every time when i install the pods it doesnt make sense . As a RN developer several time you have to delete node module .lock file and pod folder .Is there any way to avoid that particular line everytime i install the pods

**Comment by ThiagoFerreira12** [comment]
> Hey there i have checked your answer related to Pod install in ios issue when using new architecture of react native i.e 0.7x . The answer is already mentioned in the documentation by adding RCT_NEW_ARCH_ENABLED=1 when installing pod. But the thing that bother me that do i need to do that thing every time when i install the pods it doesnt make sense . As a RN developer several time you have to delete node module .lock file and pod folder .Is there any way to avoid that particular line everytime i install the pods

i having the same issue, i had downgrade the version lib for 1.1.3, after then it works

**Comment by satyabrata-dash5** [comment]
same issue with me

**Comment by vonovak** [comment]
Hello and thanks for asking,
> But the thing that bother me that do i need to do that thing every time when i install the pods it doesnt make sense 

you can, of course, create your own alias for the command so that you don't need to think about it.

enabling new architecture is required by react native, and it is documented here: https://reactnative.dev/docs/next/the-new-architecture/use-app-template#enable-the-new-architecture


Thank you 🙂
