### ISSUE TITLE
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNSimpleToast' could not  be found. Verify that a module by this name is registered in the native binary

### ISSUE THREAD

**Issue by zhenguet** [vonovak/react-native-simple-toast#34]
As title, it show this error when create a new project and test it with jest

**not use Toast**

> PS C:\Users\Dev\Documents\Demo> yarn test
> yarn run v1.22.19
> $ jest
>  PASS  __tests__/App-test.tsx
>   √ renders correctly (281 ms)
> 
> Test Suites: 1 passed, 1 total
> Tests:       1 passed, 1 total
> Snapshots:   0 total
> Time:        2.42 s
> Ran all test suites.
> Done in 4.03s.

**add Toast:**

> PS C:\Users\Dev\Documents\Demo> yarn test
> yarn run v1.22.19
> $ jest
>  FAIL  __tests__/App-test.tsx
>   ● Test suite failed to run
> 
>     Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNSimpleToast' could not be found. Verify that a module by this name is registered in the native binary.
> 
>       18 |   View,
>       19 | } from 'react-native';
>     > 20 | import Toast from 'react-native-simple-toast';
>          | ^
>       21 | import {
>       22 |   Colors,
>       23 |   DebugInstructions,
> 
>       at invariant (node_modules/invariant/invariant.js:40:15)
>       at Object.getEnforcing (node_modules/react-native/Libraries/TurboModule/TurboModuleRegistry.js:43:12)
>       at Object.getEnforcing (node_modules/react-native-simple-toast/src/NativeSimpleToast.ts:39:36)
>       at require (node_modules/react-native-simple-toast/src/index.ts:5:14)
>       at Object.<anonymous> (node_modules/react-native-simple-toast/src/index.ts:10:3)    
>       at Object.<anonymous> (App.tsx:20:1)
>       at Object.<anonymous> (__tests__/App-test.tsx:7:1)
> 
> Test Suites: 1 failed, 1 total
> Tests:       0 total
> Snapshots:   0 total
> Time:        1.522 s, estimated 2 s
> Ran all test suites.
> error Command failed with exit code 1.

**package.json**

```
{
...
"dependencies": {
    "react": "18.2.0",
    "react-native": "0.71.1",
    "react-native-simple-toast": "^2.0.0"
  },
...
}
```

**Comment by zhenguet** [comment]
#

**Comment by agnimgupta** [comment]
Hi, we are facing the same error. How did you resolve this? @zhenguet

**Comment by zhenguet** [comment]
@agnimgupta hi, I downgrade to 1.1.4

**Comment by danielnedefo** [comment]
@agnimgupta any solution?

**Comment by lfabl** [comment]
same issue

**Comment by Eldii** [comment]
Add this mock into your test file to fix the error :
`jest.mock("react-native-simple-toast", () => ({
  Toast: () => jest.fn(),
}));
`
