### ISSUE TITLE
null is not an object (evaluating 'RCTToast.SHORT')

### ISSUE THREAD

**Issue by jasuno** [vonovak/react-native-simple-toast#35]
I get this error the second I import the component

**Comment by vonovak** [comment]
hello, I'm sorry but without a runnable repro, I cannot help. The native module is probably not correctly linked.

**Comment by app-arianamini** [comment]
I have this error too, any solution?

**Comment by jengelsma** [comment]
same here, bummer.

**Comment by vonovak** [comment]
guys, can you *please* say if this is on ios or android, if you're using expo or not and ideally give a runnable reproduction?

see https://stackoverflow.com/help/mcve

thank you!

**Comment by jasuno** [comment]
Hey guys, I think I found the issue. Its because I am using Expo in my project and expo docs state that "The Payments module is currently only supported the bare workflow on iOS. If you have a managed workflow project, you'll need to move to the bare workflow in order to use this module on iOS."

I suppose you guys have the same problem. You can get more information at https://docs.expo.io/versions/latest/sdk/payments/
