### ISSUE TITLE
Unable to build on iOS

### ISSUE THREAD

**Issue by hafizMDM** [vonovak/react-native-simple-toast#39]
On android it works fine 

"react-native": "0.67.5"
"react-native-simple-toast": "^2.0.0",

![image](https://user-images.githubusercontent.com/2582410/225731326-0e05b337-15d2-4f6d-863f-c273e549b72a.png)

**Comment by hafizMDM** [comment]
FYI, It builds fine on previous 1.1.4 version.

**Comment by vonovak** [comment]
Hello and thanks for reporting,
please read the readme: https://github.com/vonovak/react-native-simple-toast#install

Thank you 🙂
