### ISSUE TITLE
[Feature] iOS toast with blurred background

### ISSUE THREAD

**Issue by replecta** [vonovak/react-native-simple-toast#4]
I wanted to do it myself but objective-c is so confusing that i got no success, It's not really important but having the background blurred with light and dark option will look awesome with the whole apple design guidelines!

**Comment by vonovak** [comment]
hi! Thanks for the feature request, I'll not implement this but you're welcome to fork this repo and add this, and maybe I'd merge such feature (depending on how it works). Thanks.
