### ISSUE TITLE
Request : Background color for toast 

### ISSUE THREAD

**Issue by wandip** [vonovak/react-native-simple-toast#4]

**Comment by webjunkie01** [comment]
1+

**Comment by vonovak** [comment]
hello, I personally will not be adding such method because as far as I'm aware, not even android has such option, and I don't need it. Thanks!

**Comment by webjunkie01** [comment]
Thanks for the reply. Yes it seems Android do not have support for visual styles.

**Comment by AlkanV** [comment]
Hello, what about for ios toast? as far as i know, it can accept style prop. @vonovak

**Comment by vonovak** [comment]
@AlkanV if you want to have it, please open a PR and I'll merge it. Thanks!

**Comment by cassioseffrin** [comment]
Hello @vonovak and @AlkanV.

I have made a fork of this project with this request done for IOS and android. It's here: https://github.com/cassioseffrin/react-native-simple-toast
You can test it direct from my github by adding the package as follow:
`yarn add 'react-native-simple-toast@https://github.com/cassioseffrin/react-native-simple-toast'
`
To test it in IOS just make the install and run:
```
foregroundColor = 0xffffff;
backgroundColor = 0x50A54A;
Toast.showWithGravity('message', Toast.SHORT, Toast.TOP, foregroundColor, backgroundColor);
```

Detailed explanation of my changes in this repo:

For IOS is just pass the the new params that will be foregroundColor and backgroundColor.
```
export const ToastColorIOS = { SUCCESS: 0x50A54A, ERROR: 0xF44336, WARN: 0xFF9800, INFO: 0x673AB7 };
Toast.showWithGravity(mensagem, Toast.SHORT, Toast.TOP, 0xffffff, ToastColorIOS[color]);
```

I also made a custom color Toast for Android. But for that was needed to customize the default toast creating a new android layouts and so on. If you need it I can share it. For android I don't think the custom toast could be wrapped direct in this library. It's needed to make it on android studio.

After all o created a react hook that according with platform call custom toast for android or IOS.

```
import { Platform } from 'react-native';
import CustomToastArpa from '../components/CustomToastArpa';
import Toast from 'react-native-simple-toast';
let gravity = [];
gravity['TOP'] = 48;
gravity['CENTER'] = 17;
gravity['BOTTOM'] = 80;
gravity['NO_GRAVITY'] = 0;
export const ToastColor = { SUCCESS: '#D950A54A', ERROR: '#D9F44336', WARN: '#E6FF9800', INFO: '#D93F51B5' };
export const ToastColorIOS = { SUCCESS: 0x50A54A, ERROR: 0xF44336, WARN: 0xFF9800, INFO: 0x673AB7 };

export const showCustomToast = (message, color, gravity) => {
	if (Platform.OS === 'android') {
		CustomToastArpa.show(message, CustomToastArpa.SHORT, ToastColor[color], gravity[gravity], 0, 90);
	} else {
		Toast.showWithGravity(message, Toast.SHORT, Toast.TOP, 0xffffff, ToastColorIOS[color]);
	}
};

```

Finally to display the Toast is just call in my app:

`showCustomToast('you message', 'SUCCESS', 'TOP');`

In case you like this solution, may I could make a PR and merge it to a new version.

Best Regards!

**Comment by AlkanV** [comment]
@cassioseffrin hello my friend, 

thank you for enormously big explanation, and i am terrible sorry for very late response, 

best regards,

a.
