### ISSUE TITLE
'RNSimpleToastSpec.h' file not found

### ISSUE THREAD

**Issue by Akilramki** [vonovak/react-native-simple-toast#40]
Unable to run the ios project

Upgrade 
from
"react-native-simple-toast": "^1.1.4"

To
 "react-native-simple-toast": "^2.0.0",

<img width="722" alt="Screenshot 2023-03-23 at 4 10 52 PM" src="https://user-images.githubusercontent.com/105835418/227178627-bc091dca-e7ec-4380-8634-7f57fc75f47e.png">

![Screenshot_1679568353](https://user-images.githubusercontent.com/105835418/227179939-38f29dd2-a59b-40f1-ac5e-8aa37b73a4a9.png)

**Comment by vonovak** [comment]
Hello and thanks for reporting,
please read the readme: https://github.com/vonovak/react-native-simple-toast#install

Thank you 🙂
