### ISSUE TITLE
Icon on toast in Android

### ISSUE THREAD

**Issue by emersoncavalcanti1972** [vonovak/react-native-simple-toast#42]
It is not clear from the documentation how the configuration of the icon displayed on Android in newer versions works. I have noticed that it initially appears with a question mark symbol, but after some message from the application, it adopts the correct icon.

It would be interesting to document how this component behaves in relation to Android itself. I don't have iOS to know if any icon appears on it.

**Comment by KiranSayone** [comment]
I do have an iOS device and i can confirm that there is no icon in iOS. But in my case in some android devices it is displaying an android icon instead of the app icon. How to fix this or how to even remove this icon completely.

**Comment by vonovak** [comment]
Hello and thanks for asking,
on android, the toast from react native core is used [see here](https://github.com/vonovak/react-native-simple-toast/blob/237bf3ec95fcf900477a329191fba6e428d23480/src/index.ts#L22)


I'm not aware of the details of how it's done there, please refer to the implementation in the react native core.

Thank you 🙂
