### ISSUE TITLE
'RNSimpleToastSpec.h' file not found

### ISSUE THREAD

**Issue by roo12312** [vonovak/react-native-simple-toast#43]
hi im getting this error on build `'RNSimpleToastSpec.h' file not found`
I'm using expo 48..

**Comment by abolfazlyounesi** [comment]
Having the same issue ...

**Comment by akshay1788** [comment]
I know this is not the correct answer but there is a temporary way to use this library without error. Install and use version 1.1.4 of react-native-simple-toast.

**Comment by DeVoresyah** [comment]
same issue

**Comment by vonovak** [comment]
Hello and thanks for asking,
please see https://github.com/vonovak/react-native-simple-toast/issues/30#issuecomment-1361240734
Thank you 🙂
