### ISSUE TITLE
In ios the toast is showing but for very short period of time but in android it is working fine.

### ISSUE THREAD

**Issue by vipul2511** [vonovak/react-native-simple-toast#5]
Toast.show(`You can not update since you have been checkout for the day`,Toast.LONG);
Using the above Toast code, It is working fine in android but in ios, the toast is showing for very short period of time that the user can't read the message.

**Comment by AndrewMarkley** [comment]
I'm having the same issue

**Comment by SDE-Arvind** [comment]
Try this 

setTimeout(() => {
      Toast.showWithGravity("MESSAGE", Toast.SHORT, Toast.CENTER);
    }, 0);

**Comment by vipul2511** [comment]
Okay I will try.

Thanks for your help.

**Comment by vonovak** [comment]
hello, I'm closing this because there is no reproduction of the issue. Please see https://stackoverflow.com/help/minimal-reproducible-example and open a new issue if problem persists, thanks!
