### ISSUE TITLE
RNSplashScreen.h not found

### ISSUE THREAD

**Issue by pawanv048** [vonovak/react-native-simple-toast#54]
Please [search issues before opening a new one](https://twitter.com/vonovak/status/1621272417187336193?s=20).

**Describe the bug**
RNSplashScreen.h not found

**To Reproduce**
install react-native simple toast
pod install
run project getting RNSplashScreen.h not found 

**Expected behavior**
I have Apple chip M1, React-native version 0.69.
I have installed the library and installed the pod as well.
the run project gets an error.

**Comment by vonovak** [comment]
Hello and thanks for asking,
this project has nothing to do with `RNSplashScreen` so not sure there.

please try with v3 of the library. Also, I recommend you use RN bootsplash instead of RNSplashScreen
Thank you 🙂
