### ISSUE TITLE
'RNSimpleToastSpec.h' file not found

### ISSUE THREAD

**Issue by Dhaval1905** [vonovak/react-native-simple-toast#56]
'RNSimpleToastSpec.h' file not found facing issue. And when I use below command it is gives me invalid pod file error.

RCT_NEW_ARCH_ENABLED=1 pod install     

React-Native version 0.70.5

**Comment by saurabhsaneja** [comment]
I solved this by downgrading package version to 1.1.4. This will use old architecture.

**Comment by vonovak** [comment]
You should be able to use version 3 with the old architecture as well

**Comment by vonovak** [comment]
Hello and thanks for reporting,
I just tested this with RN 0.71 and I cannot reproduce. The new architecture is still experimental so upgrading RN might solve your issue. 

Also note that version 3 works with the old and new architecture as well



Thank you 🙂
