### ISSUE TITLE
React Native 0.72 support?

### ISSUE THREAD

**Issue by gavrichards** [vonovak/react-native-simple-toast#57]
I just want to check if this library supports React Native 0.72.
I've used it in my app for a while, no problem at all. I've just updated my codebase from RN 0.71 to 0.72, and then updated this library from 1.1.4 to 3.0.0, but now toasts aren't appearing at all.

The only thing that's appearing in the console log at the time I present a toast which might be relevant is:
> Unbalanced calls to begin/end appearance transitions for <UIViewController: 0x11364d6b0>.

Downgrading this library to 1.1.4 while staying on RN 0.72 fixes the issue, and the toasts are back.

Thanks

**Comment by vonovak** [comment]
Hello and thanks for reporting,
I tested it on a project with 0.72 and it works for me

the warning you're getting, along with some other updates is fixed in 3.0.1 - can you give it a try? If that doesn't work then I'll need a repo that reproduces the issue

Thank you 🙂

**Comment by gavrichards** [comment]
Thank you, just tested 3.0.1 on RN 0.72 on iOS and Android and it's now working, so this is now resolved.

**Comment by vonovak** [comment]
Amazing, thanks!🙂
