### ISSUE TITLE
iOS not showing toast every time?

### ISSUE THREAD

**Issue by chapeljuice** [vonovak/react-native-simple-toast#6]
I'm seeing some weirdness where iOS is only showing the toast notification occasionally, even if I'm doing the same actions in our app. 

Anyone else experience that?

I'm calling it using both:
```
Toast.show(`${data.response.numFound} results found`)
```
and 
```
Toast.show(`${data.response.numFound} results found`, Toast.LONG, Toast.BOTTOM)
```

Some package info for reference:
```
"react": "^16.0.0-alpha.6",
"react-native": "0.44.0",
"react-native-simple-toast": "0.0.7",
```

**Comment by bithavoc** [comment]
I'm seeing this as well. I have consistent reproduction of this issue when used after an `await` call.

```
// Toast.showWithGravity('this toast always works', Toast.LONG, Toast.BOTTOM);
let result = await AuthenticationService.authenticate(this.state);
Toast.showWithGravity('this toast never works', Toast.LONG, Toast.BOTTOM);
```

**Comment by amitbravo** [comment]
did you try settimeout ? e.g. 
setTimeout(() => {
                                 Toast.show(msg,Toast.LONG)
                                 }, 100)

**Comment by vonovak** [comment]
closing as there is no runnable repro. Please open a new issue if the problem persists. Thanks.
