### ISSUE TITLE
Expo error -  TypeError: null is not an object (evaluating 'RCTToast.SHORT')

### ISSUE THREAD

**Issue by borakuldeep** [vonovak/react-native-simple-toast#7]
It gives error for iOS. Android works fine. I am using expo and installed the library using npm.

**Comment by vonovak** [comment]
hello, this library has a custom native module for ios, and expo does not support that. This lib will not work with expo, sorry

**Comment by AdnanAshraf-gol** [comment]
It worked for me with expo in bare work flow .. just reinstall the app..
