### ISSUE TITLE
Unknown type name 'RCT_EXTERN_C_END'

### ISSUE THREAD

**Issue by ignivaravinderrikhi** [vonovak/react-native-simple-toast#8]
Unable to create build getting errors on Xcode "LRDRCTSimpleToast":

![screen shot 2018-01-30 at 4 38 12 pm](https://user-images.githubusercontent.com/20724772/35565946-9cbf10aa-05e5-11e8-8504-57e9feed7ba6.png)
![screen shot 2018-01-30 at 4 38 28 pm](https://user-images.githubusercontent.com/20724772/35565949-9df49526-05e5-11e8-9dfd-7058d81b6a40.png)

:

**Comment by vonovak** [comment]
closing as it's pretty old.
